FROM python:3.7

ARG BM_CAT_SSL_CERTIFICATE_PATH
ARG BM_CAT_PRIVATE_KEY_PATH
ARG PORT
ARG BM_CAT_HOST
ARG BM_CAT_PORT
ARG BM_CAT_API_KEY
ARG BM_YOUTUBE_API_KEY

ENV BM_CAT_SSL_CERTIFICATE_PATH=$BM_CAT_SSL_CERTIFICATE_PATH
ENV BM_CAT_PRIVATE_KEY_PATH=$BM_CAT_PRIVATE_KEY_PATH
ENV PORT=$PORT
ENV BM_CAT_HOST $BM_CAT_HOST
ENV BM_CAT_PORT $BM_CAT_PORT
ENV BM_CAT_API_KEY $BM_CAT_API_KEY
ENV BM_YOUTUBE_API_KEY $BM_YOUTUBE_API_KEY
ENV PYTHONPATH /bm-cat/

ADD public.pem $BM_CAT_SSL_CERTIFICATE_PATH
ADD private.key $BM_CAT_PRIVATE_KEY_PATH

COPY . /bm-cat/

WORKDIR /bm-cat

RUN pip install -r requirements.txt
RUN export PYTHONPATH=/bm-cat/

EXPOSE $PORT

CMD ["python","src/server.py"]
